<VerificationJob>
  <Configuration>
    <AnalyzeChecksIndividually value="false" />
    <BitcodeTraces value="false" />
    <EnableSlicing value="false" />
    <EntryPoint value="unpack_gyro_data" />
    <FixPoint value="true" />
    <HavocLimit value="1" />
    <IgnoreMissingFunctions value="false" />
    <InitializedGlobals value="false" />
    <LoopUnrollBound value="12" />
    <OverApproxVaArgs value="false" />
    <PreconditionLocation value="jobs/195" />
    <SourceDirectory value="/home/i12/mbuening/100_Dissertation/BMI160/BMI160_driver" />
    <StopEncodingAfterCheck value="false" />
    <StopEncodingAfterCheckLoop value="0" />
    <TimeOut value="300" />
  </Configuration>
  <CheckList>
    <Check id="2338" location="2483" category="arithmetic.overflow.warning" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>An unsigned arithmetic operation can overflow (wraparound).</Annotation>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
    <Check id="2341" location="2486" category="explicit.conversion.overflow" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
    <Check id="2344" location="2487" category="shift.of.negative" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
    <Check id="2348" location="2491" category="arithmetic.overflow.warning" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
    <Check id="2354" location="2495" category="shift.of.negative" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
    <Check id="2358" location="2499" category="arithmetic.overflow.warning" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
    <Check id="2360" location="2501" category="arithmetic.overflow.warning" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
    <Check id="2364" location="2503" category="shift.of.negative" status="internalerror" scope="unpack_gyro_data">
      <Annotations>
        <Annotation>The model checker terminated with an exception (job:195)</Annotation>
      </Annotations>
    </Check>
  </CheckList>
  <Annotation>The model checker terminated with an exception</Annotation>
  <Status>internalerror</Status>
</VerificationJob>
